cc_test (
    name = "rainbow-test",
    srcs = [
        "gf16-test.cc",
    ],
    deps = [
        "//src/main:timing-functions",
        "//src/lib:rainbow",
        "@gtest//:gtest_main",
    ],
)